name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

        # new added 
      - name: Setup Node.js (for Tailwind CSS)
        uses: actions/setup-node@v3
        with:
          node-version: '18'


      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

        # new added 
      - name: Install npm dependencies (Tailwind, Vite, etc.)
        run: npm install

        # new added 
      - name: Build Tailwind CSS (Vite/Mix)
        run: npm run build

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        run: vendor/bin/phpunit